---
###Example pour launch une instance###
###ansible-playbook --extra-vars "hosts=ansible-test"###
- hosts: localhost
##Init variable##
  vars:
    keypair: "AWS-KEYS-WEBSERVER001"
    instance_type: t2.micro
    hosts: "{{ hosts }}"
    groups: "Web"
    image: "ami-0ea4a063871686f37"

  tasks:
            
    - name: startup new instance
      community.aws.ec2_instance:
         key_name: "{{ keypair }}"
         security_group: "Web"
         instance_type: "{{ instance_type }}"
         name: "fermela"
         image_id: "{{ image }}"
         wait: true
         region: "eu-west-3"
         network:
           assign_public_ip: true
         vpc_subnet_id: "subnet-0c82e6027833af6cc"
      register: ec2
   
    - debug :
            var: ec2.instances[0].public_ip_address
